apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/cert-manager
patches:
  - patch: |
      - op: replace
        path: /data/values.yaml
        value: |
          installCRDs: true
          replicaCount: 1
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              memory: 64Mi
    target:
      kind: ConfigMap
      name: cert-manager-values
