---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
patches:
  - target:
      kind: Deployment
      name: my-app
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: nginx:1.25.0-alpine  # Smaller image for staging
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: "25m"
  - target:
      kind: Ingress
      name: my-app
    patch: |-
      - op: replace
        path: /spec/tls/0/hosts/0
        value: my-app.staging.example.com
      - op: replace
        path: /spec/rules/0/host
        value: my-app.staging.example.com
