#!/usr/bin/env bash
# Generated by platform-skills setup-agents
PASS=0; FAIL=0

check() {
  if bash -c -- "$2" &>/dev/null; then echo "✓ $1"; ((PASS++))
  else echo "✗ $1"; ((FAIL++)); fi
}

info() { echo "ℹ️  $1 (not generated for this repo)"; }

echo "=== Agent setup verification ==="
check "AGENTS.md present" "test -f AGENTS.md"

GENERATED_COPILOT=true
GENERATED_COPILOT_APP=false
GENERATED_VSCODE_MCP=false
GENERATED_CURSOR=false
GENERATED_CODEX=true

if [ "$GENERATED_COPILOT" = true ]; then
  check "Copilot agent files" "ls .github/agents/*.agent.md"
else
  info "Copilot agents"
fi

if [ "$GENERATED_COPILOT_APP" = true ]; then
  check "Cloud agent configured" "test -f .github/copilot-setup-steps.yml"
else
  info "Copilot App setup"
fi

if [ "$GENERATED_VSCODE_MCP" = true ]; then
  check "MCP wired (VS Code)" "grep -q mcpServers .vscode/settings.json"
else
  info "VS Code MCP"
fi

if [ "$GENERATED_CURSOR" = true ]; then
  check "Cursor rules present" "test -d .cursor/rules && ls .cursor/rules/*.mdc"
else
  info "Cursor rules"
fi

if [ "$GENERATED_CODEX" = true ]; then
  check "Codex config present" "test -f agents/openai.yaml"
else
  info "Codex config"
fi

echo "--- Checking agent file references (staleness) ---"
# Only scan agent files generated by platform-skills setup-agents.
# Pre-existing .cursor/rules/*.mdc contain domain examples (Terraform filenames,
# Kubernetes API group strings) that are intentionally not repo paths.
for agent in .github/agents/*.agent.md; do
  [ -f "$agent" ] || continue
  # Strip fenced code blocks (``` ... ```) and URLs before path extraction.
  # Code blocks contain commands (git remote paths, grep patterns) that are not file refs.
  AGENT_LINES=$(awk '/^```/{skip=!skip; next} !skip{print}' "$agent" \
    | grep -vE 'https?://')
  # Only check paths that contain at least one '/' — bare filenames in prose are not checked.
  # This avoids false positives from template text (<name>-generate.md), source.sha → source.sh,
  # and bare filenames in table cells or inline descriptions.
  while read -r p; do
    test -f "$p" || { echo "⚠️  $agent references missing file: $p"; ((FAIL++)); }
  done < <(printf '%s\n' "$AGENT_LINES" \
    | grep -oE '\.?[a-zA-Z0-9_][a-zA-Z0-9_-]*(/[a-zA-Z0-9_.@-]+)+\.(py|ts|go|tf|yaml|yml|json|md|sh)' \
    | grep -vE '^example/' \
    | grep -vE '<[a-zA-Z]')
  while read -r d; do
    test -d "${d%/}" || { echo "⚠️  $agent references missing directory: $d"; ((FAIL++)); }
  done < <(printf '%s\n' "$AGENT_LINES" \
    | grep -oE '\.?[a-zA-Z][a-zA-Z0-9_-]+/[a-zA-Z0-9_-]+/' \
    | grep -vE '<[a-zA-Z]' \
    | sort -u)
done

echo "--- $PASS passed, $FAIL issues ---"
exit $((FAIL > 0))
