// @ts-check

/**
 * Sidebar stubs — replaced by Task 3 with full auto-generated sidebars.
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  referencesSidebar: [{ type: 'autogenerated', dirName: '.' }],
  commandsSidebar: [{ type: 'autogenerated', dirName: '.' }],
};

module.exports = sidebars;
